### ISSUE TITLE
Add support for commit messages using stage

### ISSUE THREAD

**Issue by RemeJuan** [MikeMitterer/dart-changelog#4]
Currently this package is not working with my repo as we format all our commits to use stages as well as semantic tags

`feat(auth): Updated user auth flow`

Currently using a node package https://www.npmjs.com/package/auto-changelog, but putting node dependancies in a flutter projects a bit nasty.

**Comment by MikeMitterer** [comment]
Sorry but I have ditched Dart completely. I moved to TS about a year ago. Dart isn't even on my HD anymore.
